FROM python:3.9

WORKDIR /home

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip setuptools wheel
RUN apt-get update 
RUN apt-get install -y netcat-openbsd
RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY . /home

ENV FLASK_APP=app.py
EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
